name: merchant_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.4.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.4.0
  flutter_screenutil: ^5.4.0+1
  flutter_svg: ^1.1.4
  get: 4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  oktoast: ^3.1.5
  optimized_cached_image: ^3.0.1
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  vibration: ^1.7.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
        - asset: fonts/Manrope-Bold.ttf
        - asset: fonts/Manrope-ExtraBold.ttf
        - asset: fonts/Manrope-ExtraLight.ttf
        - asset: fonts/Manrope-Light.ttf
        - asset: fonts/Manrope-Medium.ttf
